### ISSUE TITLE
Episode name substitutions for series name?

### ISSUE THREAD

**Issue by oli-ver** [disaster123/episodescanner#1]
Hello disaster123,

is there a possibility to use the episode name substitutions for series names as well?

I. e. the german station "RTL2" uses the title "Game of Thrones - Das Lied von Eis und Feuer" for the series "Game of Thrones". As episode title they mix the english and german forms, so sometimes you cannot find the series on the english version of the tv sites you use with episodescanner.

I already tried to find something about it in the code, because in the docs this topic is not described, but to program Perl is not something of my greatest strengths :-)

Thank you very much in advance,

Oliver

**Comment by disaster123** [comment]
am besten nen anderen EPG nehmen. z.B: TvMovie ;-)

Am 01.03.2014 12:54, schrieb Oliver:

**Comment by oli-ver** [comment]
Hab ja Clickfinder, das ist doch tv Movie oder? :-)

Lasse aktuell vor der Suche ein SQL laufen, das diese Titel umbenennt. Schöner wäre natürlich einfach deine Substitutionen zu benutzen nur halt einfach für die Titel der Serie anstelle der Episodennamen. Ansonsten echt geniales Tool. Wüsste nicht wie das ohne Episodenscanner gehen soll :-)

**Comment by oli-ver** [comment]
Ich habe das Problem jetzt gelöst, indem ich eine ähnliches Tool geschrieben hab, das auf Java basiert ( ich kann Perl nicht leiden :-) ). Unterstützt Serien- und Episoden-Namen-Ersetzungen. Kannst du dir gerne mal anschauen: https://github.com/oli-ver/MPEpisodeNumberGenerator
